name: Build PearOS-Arch ISO

on:
  push:
    tags:
      - 'iso*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Archlinux
        run: curl -L https://github.com/SomethingGeneric/github-actions-archlinux/raw/master/install.sh | sh
      - name: Pacman requirements
        run: sudo pacman -Syu --noconfirm pacman-contrib archiso arch-install-scripts